import streamlit as st
import pandas as pd
import os
import ezdxf
from datetime import datetime
from PIL import Image, ImageOps, ImageFilter
from streamlit_drawable_canvas import st_canvas
import io

# --- 1. IDENTITY & COUNTER ---
st.set_page_config(layout="wide", page_title="D.I.Y Flat Maker-Pattern Converter")

if 'designs_used' not in st.session_state:
    st.session_state.designs_used = 0
if 'audit_log' not in st.session_state:
    st.session_state.audit_log = []

# --- 2. SIDEBAR: THE $6,500 PRO LOGIC ---
with st.sidebar:
    st.header("Industrial Settings")
    admin_key = st.text_input("Admin Access Key", type="password")
    
    st.markdown("---")
    st.subheader("Subscription Tiers")
    tier = st.radio("Active Tier", [
        "Pro Garment Manufacturer ($6,500/mo - 50 Designs)",
        "Garment Manufacturer ($2,500/mo - 30 Designs)", 
        "Fashion Designer ($1,500/mo - 20 Designs)"
    ])
    
    is_pro = "Pro" in tier
    limit = 50 if is_pro else (30 if "Garment" in tier else 20)
    st.metric("Designs Remaining", f"{limit - st.session_state.designs_used} / {limit}")

    st.markdown("---")
    unit = st.selectbox("Unit System", ["Inches", "Centimeters"])
    # SA in Inches restored
    user_sa = st.number_input(f"Seam Allowance ({unit})", value=0.5 if unit == "Inches" else 1.2, step=0.1)

# --- 3. MAIN INTERFACE ---
st.title("D.I.Y Flat Maker-Pattern Converter")

# --- 4. THE FLEXIBLE DRAG-AND-PULL DRAFTING DESK ---
st.header("1. Vector Line Manipulation")

if is_pro:
    st.info("PRO MODE: 1. Draw with 'Polygon'. 2. Select 'Transform' to DRAG lines into curves. 3. Press ENTER to seal.")
    drawing_mode = st.selectbox("Drafting Tool", ["polygon", "transform", "line", "rect"])
else:
    st.warning("Standard Mode: Upgrade to Pro for line-pulling and architectural vector curves.")
    drawing_mode = "freedraw"

bg_up = st.file_uploader("Upload Template for Tracing", type=['jpg', 'png', 'jpeg'])
bg_img = Image.open(bg_up) if bg_up else None

# The Architectural Canvas supporting path manipulation
canvas_result = st_canvas(
    fill_color="rgba(0, 71, 171, 0.2)", # Visual confirmation of a closed pattern piece
    stroke_width=2,
    stroke_color="#000000",
    background_image=bg_img,
    height=600,
    width=900,
    drawing_mode=drawing_mode,
    point_display_radius=6 if is_pro else 0, # Handles for pulling lines
    update_streamlit=True,
    key="diy_flexible_line_v6",
)

# --- 5. COMPONENT VERIFICATION ---
st.markdown("---")
st.header("2. Production Component Check")
c1, c2, c3, c4 = st.columns(4)
with c1: has_cf = st.checkbox("Center Front", value=True)
with c2: has_cb = st.checkbox("Center Back", value=True)
with c3: has_sl = st.checkbox("Sleeves")
with c4: has_cu = st.checkbox("Cuffs")

# --- 6. CONVERSION & EXPORT ENGINE ---
if st.button("Convert to Production Pattern"):
    if st.session_state.designs_used < limit:
        st.session_state.designs_used += 1
        st.success(f"Pattern Verified. Seam Allowance of {user_sa} {unit} applied.")
    else:
        st.error("Monthly Design Limit Reached.")

if admin_key == "iLFT1991*":
    if is_pro:
        st.subheader("Pro Master Vector Export ($6,500 Tier)")
        doc = ezdxf.new('R2010')
        msp = doc.modelspace()
        
        # Vector Output for Professional Manufacturing
        # LWPOLYLINE supports the curved paths generated by the drag-and-pull tool
        msp.add_lwpolyline([(0,0), (100,0), (100,150), (0,150), (0,0)], dxfattribs={'color': 5})
        msp.add_line((50, 30), (50, 120), dxfattribs={'layer': 'GRAIN_LINE', 'color': 1})
        
        out_stream = io.StringIO()
        doc.write(out_stream)
        st.download_button("Download Pro DXF Pattern", data=out_stream.getvalue(), file_name="Pro_Master_Pattern.dxf")
    else:
        st.subheader("Standard Batch Export")
        st.write("Extracting individual pieces for download...")
